### ISSUE TITLE
USDx Bounty Test

### ISSUE THREAD

**Issue by zhangjiannan** [zhangjiannan/hackerlink#11]
Testing for USDx bounty

**Comment by helloDoraHacks** [comment]
The issue has been marked as a [HackerLink Bounty](https://hackerlink.io/bounty/11).

* Bonus: **2** USDx

* Deadline: 2020-11-13T16:13:07.000Z

Record on the blockchain: `0x0d1d915e079b3c7a3f70656bb219ed26d08419974ef48ed4472e86523bfc7369`

[on Etherscan](https://etherscan.io/tx/0x0d1d915e079b3c7a3f70656bb219ed26d08419974ef48ed4472e86523bfc7369)
