### ISSUE TITLE
BUSD Competition

### ISSUE THREAD

**Issue by zhangjiannan** [zhangjiannan/hackerlink#13]
Test BUSD Bounty

**Comment by helloDoraHacks** [comment]
The issue has been marked as a [HackerLink Bounty](https://hackerlink.io/bounty/12).

* Bonus: **2** BUSD

* Deadline: 2020-11-13T16:31:25.000Z

Record on the blockchain: `0xf2c274e8566171ecc44545a1242a0f0cdbf033073ac4301b36267613200a71eb`

[on Etherscan](https://etherscan.io/tx/0xf2c274e8566171ecc44545a1242a0f0cdbf033073ac4301b36267613200a71eb)
