### ISSUE TITLE
ETH Competition

### ISSUE THREAD

**Issue by zhangjiannan** [zhangjiannan/hackerlink#6]

**Comment by helloDoraHacks** [comment]
The issue has been marked as a [HackerLink Bounty](https://hackerlink.io/bounty/8).

* Bonus: **0.1** ETH

* Deadline: 2020-11-11T11:31:38.000Z

Record on the blockchain: `0x5040df476e9a9891d8aa81f1ffdf2a61af923c63d441e8b0f97b9f9e234e4e63`

[on Etherscan](https://etherscan.io/tx/0x5040df476e9a9891d8aa81f1ffdf2a61af923c63d441e8b0f97b9f9e234e4e63)
