### ISSUE TITLE
Stable Coin Competition 2

### ISSUE THREAD

**Issue by zhangjiannan** [zhangjiannan/hackerlink#9]

**Comment by helloDoraHacks** [comment]
The issue has been marked as a [HackerLink Bounty](https://hackerlink.io/bounty/9).

* Bonus: **0.0000** USDT

* Deadline: 2020-11-12T07:38:20.000Z

Record on the blockchain: `0x891a3b4108113af66d2243f89e0f2564d9b05e5f3be8b34fd1bf40f7811ab7b0`

[on Etherscan](https://etherscan.io/tx/0x891a3b4108113af66d2243f89e0f2564d9b05e5f3be8b34fd1bf40f7811ab7b0)
